### ISSUE TITLE
DMC Notification is not working!!

### ISSUE THREAD

**Issue by siddharthajuprod07** [snehilvj/dash-mantine-components#290]
Is there any recent update happened to DMC 0.14 which broke the notification? Even the documentation website notification is also not working.

**Comment by AnnMarieW** [comment]
Hi @siddharthajuprod07 

I've also noticed this and have been trying to fix the docs.  I think the latest release of the upstream Mantine library may have broken the dmc.Notification.    They made a lot of changes to both the Notification component and it's CSS file. See the [ Mantine 7.12release notes](https://github.com/mantinedev/mantine/releases/tag/7.12.0) for more details.

In a Dash app using dmc we typically include the Notifications CSS as an external stylesheet like this:
```python
 app = Dash(external_stylesheets=["https://unpkg.com/@mantine/notifications@7/styles.css"])
```

However, that will load the latest 7.12 stylesheet that only works with Mantine V7.12.   Could you please try running your app using this 7.6.2 stylesheet that dmc uses?:

 "https://unpkg.com/@mantine/notifications@7.6.2/styles.css",

If this works for you, please let me know

**Comment by Hunknown** [comment]
Hi @AnnMarieW ,

I'm also facing the same issue in my Dash App. Thank you for your input, it helped me finding a workaround.

Your solution didn't work at first, but, after debugging the css a bit, I've noticed that there was a change in the class name in Mantine V7.12 stylesheet. In the html, the notification class name is `m_b37d9ac7` while in V7.6.2 stylesheet, it's `m-b37d9ac7` (a **dash** instead of an **underscore**).

It seems that even if dmc is based on V7.6.2, it uses class names from the latest version of Mantine.

So the workaround I found is to change the stylesheet link as you said, and add the `className="m-b37d9ac7"` to `dmc.NotificationProvider` definition. It's not perfect, but I can't see any faster way to fix it.

Another way would be to add the content of the external stylesheet to `custom.css` with the proper class name (`m_b37d9ac7`).

**Comment by siddharthajuprod07** [comment]
@AnnMarieW ,

Many thanks for your input but after applying both the CSS version change and the class name change mentioned by @Hunknown it didn't solved the issue for me.  I can see the notification but its covering the entire DIV.

PFA the screenshot. 
<img width="1275" alt="Screenshot 2024-08-07 132537" src="https://github.com/user-attachments/assets/45ad8bc6-393d-4866-82a8-fe8f1c1dfbeb">

Is there any other change I have to do?

**Comment by Hunknown** [comment]
Hi @siddharthajuprod07 ,

Yeah, that's what I had after changing the link to the external stylesheet as mentionned by @AnnMarieW . It seems that it doesn't find the css or the stylesheet is not properly added.

Check in `Sources` tab in your webbrowser inspect window (CTRL+MAJ+I on Chrome), you should have this:
![image](https://github.com/user-attachments/assets/f5bd7890-7105-44ac-93be-cb57c6f9c042)

The content should be similar to https://unpkg.com/@mantine/notifications@7.6.2/styles.css. If you don't have unpkg.com, it means you haven't properly added your external stylesheet in your `app.py`.

Another way to do it without the external stylesheet and the className is to create a `custom.css` file in the subfolder `\assets\css` of your project path and paste the following css:
``` css
.m_b37d9ac7 {
  width: calc(100% - var(--mantine-spacing-md) * 2);
  position: fixed;
  z-index: var(--notifications-z-index);
  top: var(--notifications-top);
  left: var(--notifications-left);
  right: var(--notifications-right);
  bottom: var(--notifications-bottom);
  transform: var(--notifications-transform);
  max-width: var(--notifications-container-width);
}

.m_5ed0edd0 + .m_5ed0edd0 {
    margin-top: var(--mantine-spacing-md);
  }
```
